-- Banco dedicado à amostra TRT16. Não modifica tabelas de outros projetos.
begin;
create table if not exists public.trt16_atos (
 id bigint generated by default as identity primary key,
 tipo text not null check (tipo in ('Portaria','Resolução')),
 numero integer not null, ano integer not null, titulo text not null,
 data_catalogo date, autor text, resumo text not null,
 origem text not null, coleta date not null,
 pdf_url text, pdf_observacao text, campo_busca text not null,
 unique(tipo,numero,ano)
);
create index if not exists trt16_atos_tipo_ano on public.trt16_atos(tipo,ano);
create index if not exists trt16_atos_busca on public.trt16_atos using gin(to_tsvector('simple',campo_busca));
alter table public.trt16_atos enable row level security;
revoke all on public.trt16_atos from anon, authenticated;
grant select on public.trt16_atos to anon, authenticated;
drop policy if exists trt16_leitura_publica on public.trt16_atos;
create policy trt16_leitura_publica on public.trt16_atos for select to anon,authenticated using (true);

create or replace function public.trt16_pesquisar(q text default '',tipo_filtro text default '',ano_filtro integer default null,numero_filtro integer default null)
returns jsonb language sql stable security invoker set search_path = '' as $$
 with termos as (
 select to_tsquery('simple', string_agg(quote_literal(token)||':*',' & ')) as consulta
 from regexp_split_to_table(regexp_replace(left(q,300),'[^[:alnum:]_]+',' ','g'),'\s+') as token where token<>''
 ), filtrados as (
 select a.* from public.trt16_atos a cross join termos t
 where (t.consulta is null or to_tsvector('simple',a.campo_busca) @@ t.consulta)
 and (tipo_filtro='' or a.tipo=tipo_filtro)
 and (ano_filtro is null or a.ano=ano_filtro)
 and (numero_filtro is null or a.numero=numero_filtro)
 ), pagina as (select * from filtrados order by ano desc,numero desc limit 100)
 select jsonb_build_object(
 'resultados',coalesce((select jsonb_agg(to_jsonb(p)-'campo_busca' order by ano desc,numero desc) from pagina p),'[]'::jsonb),
 'encontrados',(select count(*) from filtrados),
 'total',(select count(*) from public.trt16_atos),
 'anos',coalesce((select jsonb_agg(ano order by ano desc) from (select distinct ano from public.trt16_atos) y),'[]'::jsonb))
$$;
revoke all on function public.trt16_pesquisar(text,text,integer,integer) from public;
grant execute on function public.trt16_pesquisar(text,text,integer,integer) to anon,authenticated;
commit;
