begin;
insert into public.trt16_atos (tipo,numero,ano,titulo,data_catalogo,autor,resumo,origem,coleta,pdf_url,pdf_observacao,campo_busca) values
('Portaria',472,2026,'Portaria da Presidência nº 472/2026','2026-06-12','José Evandro de Souza','Exoneração, a pedido, de Marcos Vinícius Ferreira de Oliveira do cargo de Analista Judiciário, com efeitos a partir de 26 de maio de 2026. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/entities/publication/6d1a2bbe-6396-48e7-8c5d-36592f6fbdc7/full','2026-10-02',null,'O registro oficial informa um PDF (77,18 KB), mas o endereço direto não pôde ser obtido. Na página do registro, procure Arquivos e Baixar.','portaria da presidencia nº 472/2026 jose evandro de souza exoneracao, a pedido, de marcos vinicius ferreira de oliveira do cargo de analista judiciario, com efeitos a partir de 26 de maio de 2026. resumo elaborado para o prototipo.'),
('Portaria',112,2024,'Portaria da Presidência nº 112/2024','2024-02-08','Márcia Andrea Farias da Silva','O catálogo informa cancelamento da edição do ato normativo. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/browse/author?scope=fb1166f6-d480-41b0-a09b-26b7f63b2c55&value=M%C3%A1rcia+Andrea+Farias+da+Silva','2026-10-02',null,'PDF não localizado nesta consulta. Consulte a biblioteca oficial.','portaria da presidencia nº 112/2024 marcia andrea farias da silva o catalogo informa cancelamento da edicao do ato normativo. resumo elaborado para o prototipo.'),
('Portaria',119,2024,'Portaria da Presidência nº 119/2024','2024-02-16','Márcia Andrea Farias da Silva','O catálogo informa cancelamento da edição do ato normativo. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/browse/author?scope=fb1166f6-d480-41b0-a09b-26b7f63b2c55&value=M%C3%A1rcia+Andrea+Farias+da+Silva','2026-10-02',null,'PDF não localizado nesta consulta. Consulte a biblioteca oficial.','portaria da presidencia nº 119/2024 marcia andrea farias da silva o catalogo informa cancelamento da edicao do ato normativo. resumo elaborado para o prototipo.'),
('Resolução',31,2026,'Resolução Administrativa nº 31/2026','2026-03-20','Samyra Antonia Maia Pereira Braga','Marcação de férias da desembargadora Solange Cristina Passos de Castro. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/entities/publication/b9bcbd2c-3353-497a-bc3d-9c58c8156d4f','2026-10-02',null,'PDF não localizado nesta consulta. Consulte a biblioteca oficial.','resolucao administrativa nº 31/2026 samyra antonia maia pereira braga marcacao de ferias da desembargadora solange cristina passos de castro. resumo elaborado para o prototipo.'),
('Resolução',120,2026,'Resolução Administrativa nº 120/2026','2026-07-21','Mônica Bezerra de Araújo Lindoso','Aprovação da ata de correição da Vara do Trabalho de Bacabal/MA referente a 2026. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/browse/author?scope=0bd21984-5ce9-4b34-9040-052b857ad0c9&value=M%C3%B4nica+Bezerra+de+Ara%C3%BAjo+Lindoso','2026-10-02',null,'PDF não localizado nesta consulta. Consulte a biblioteca oficial.','resolucao administrativa nº 120/2026 monica bezerra de araujo lindoso aprovacao da ata de correicao da vara do trabalho de bacabal/ma referente a 2026. resumo elaborado para o prototipo.'),
('Resolução',121,2026,'Resolução Administrativa nº 121/2026','2026-07-21','Mônica Bezerra de Araújo Lindoso','Aprovação da ata de correição da 5ª Vara do Trabalho de São Luís/MA referente a 2026. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/browse/author?scope=0bd21984-5ce9-4b34-9040-052b857ad0c9&value=M%C3%B4nica+Bezerra+de+Ara%C3%BAjo+Lindoso','2026-10-02',null,'PDF não localizado nesta consulta. Consulte a biblioteca oficial.','resolucao administrativa nº 121/2026 monica bezerra de araujo lindoso aprovacao da ata de correicao da 5ª vara do trabalho de sao luis/ma referente a 2026. resumo elaborado para o prototipo.'),
('Resolução',125,2026,'Resolução Administrativa nº 125/2026','2026-09-09','Mônica Bezerra de Araújo Lindoso','Deferimento de vitaliciamento de Larissa Alcântara Freire Siebra como Juíza do Trabalho Substituta do TRT16. Resumo elaborado para o protótipo; corrigido após nova consulta à listagem oficial.','https://bibliotecadigital.trt16.jus.br/browse/author?scope=0bd21984-5ce9-4b34-9040-052b857ad0c9&value=M%C3%B4nica+Bezerra+de+Ara%C3%BAjo+Lindoso','2026-10-02',null,'PDF não localizado nesta consulta. Consulte a biblioteca oficial.','resolucao administrativa nº 125/2026 monica bezerra de araujo lindoso deferimento de vitaliciamento de larissa alcantara freire siebra como juiza do trabalho substituta do trt16. resumo elaborado para o prototipo; corrigido apos nova consulta a listagem oficial.'),
('Resolução',124,1992,'Resolução Administrativa nº 124/1992','1992-09-02','Mônica Bezerra de Araújo Lindoso','Aprovação do regulamento de progressão e ascensão funcionais do Tribunal. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/browse/author?scope=0bd21984-5ce9-4b34-9040-052b857ad0c9&value=M%C3%B4nica+Bezerra+de+Ara%C3%BAjo+Lindoso','2026-10-02',null,'PDF não localizado nesta consulta. Consulte a biblioteca oficial.','resolucao administrativa nº 124/1992 monica bezerra de araujo lindoso aprovacao do regulamento de progressao e ascensao funcionais do tribunal. resumo elaborado para o prototipo.'),
('Portaria',163,2026,'Portaria da Presidência nº 163/2026','2026-02-27','José Evandro de Souza','Altera a composição do grupo de trabalho para elaboração de manual sobre gestão de precatórios e requisições de pequeno valor, instituído pela Portaria nº 472/2024. Resumo elaborado para o protótipo.','https://bibliotecadigital.trt16.jus.br/browse/author?scope=fb1166f6-d480-41b0-a09b-26b7f63b2c55&value=Jos%C3%A9+Evandro+de+Souza','2026-10-02','https://bibliotecadigital.trt16.jus.br/server/api/core/bitstreams/e3caee64-5441-4835-a9b5-217a92742568/content','Endereço oficial identificado em conteúdo PDF indexado. O acesso direto falhou nesta sessão; o arquivo depende da disponibilidade da biblioteca. Não há cópia local.','portaria da presidencia nº 163/2026 jose evandro de souza altera a composicao do grupo de trabalho para elaboracao de manual sobre gestao de precatorios e requisicoes de pequeno valor, instituido pela portaria nº 472/2024. resumo elaborado para o prototipo.'),
('Resolução',168,2025,'Resolução Administrativa nº 168/2025',null,null,'Ato de 11/09/2025, vinculado ao protocolo administrativo SEI nº 000006152-2025. PDF identificado pelo cabeçalho indexado; ementa e autoria não confirmadas.','https://bibliotecadigital.trt16.jus.br/handle/123456789/3','2026-10-02','https://bibliotecadigital.trt16.jus.br/server/api/core/bitstreams/7a277ff6-0f83-444d-b170-53108f8ddd1f/content','Endereço oficial identificado em conteúdo PDF indexado. O acesso direto falhou nesta sessão; o arquivo depende da disponibilidade da biblioteca. Não há cópia local.','resolucao administrativa nº 168/2025  ato de 11/09/2025, vinculado ao protocolo administrativo sei nº 000006152-2025. pdf identificado pelo cabecalho indexado; ementa e autoria nao confirmadas.')
on conflict (tipo,numero,ano) do update set titulo=excluded.titulo,data_catalogo=excluded.data_catalogo,autor=excluded.autor,resumo=excluded.resumo,origem=excluded.origem,coleta=excluded.coleta,pdf_url=excluded.pdf_url,pdf_observacao=excluded.pdf_observacao,campo_busca=excluded.campo_busca;
-- Compatibilidade: preservar os dois links existentes sem presumir a categoria.
insert into public.trt16_arquivos(ato_id,url,nome,categoria,descricao,coleta)
select id,pdf_url,'PDF identificado','nao_classificado',pdf_observacao,coleta
from public.trt16_atos where pdf_url is not null
on conflict (url) do nothing;
commit;
